<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Admin\Categories\Delete\" />
    <Folder Include="Admin\Categories\Grid\" />
    <Folder Include="Admin\Categories\Read\" />
    <Folder Include="Admin\Categories\Update\" />
    <Folder Include="Commons\" />
    <Folder Include="Site\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
